version: '3.7'


services:

  websiteclient:
    container_name: web-site-client
    build:
      context: .
      dockerfile: WebClient.Dockerfile
    depends_on:
      - mywebsite

  mywebsite:
    container_name: my-web-site
    build:
      context: .
      dockerfile: HttpServer.Dockerfile
    ports:
      - "5005:8080"
    stdin_open: true
    tty: true
