version: '3.7'

networks:
  ntwclientandserver:
    driver: bridge

services:
  mywebsite:
    container_name: my-web-site
    build:
      context: .
      dockerfile: HttpServer.Dockerfile
    networks:
      - ntwclientandserver
    entrypoint: /bin/sh
  websiteclient:
    container_name: web-site-client
    build:
      context: .
      dockerfile: WebClient.Dockerfile
    depends_on:
      - mywebsite
    networks:
      - ntwclientandserver